### ISSUE TITLE
Create login screen

### ISSUE THREAD

**Issue by CarlosCRG19** [Bugs-io/ibm-dashboard-app#3]
### Acceptance criteria 
* It has a form with two fields:
    * Mail
    * Password
* The form is accompanied by a disabled "Login" button
* The mail field verifies that it complies with the conventional mail format (user@domain.tld)
    *  _If the mail does not comply with this format, a legend is displayed indicating that the format is incorrect_
* When both fields are entered the "Login" button is enabled
* Clicking on the "Login" button executes an http request to the server with the mail and password as body

**Comment by CristianCazares** [comment]
Solved with: #4
