### ISSUE TITLE
Create sign up screen

### ISSUE THREAD

**Issue by CarlosCRG19** [Bugs-io/ibm-dashboard-app#5]
### Acceptance criteria 
* It has a form with two fields:
    * Mail
    * Password
* The form is accompanied by a disabled "Register" button
* The mail field verifies that it complies with the conventional mail format (user@domain.tld)
    *  _If the mail does not comply with this format, a legend is displayed indicating that the format is incorrect_
* The password field verifies that it meets the following requirements:
    * minimum length of 6 characters
    * inclusion of numbers (at least one)
    * _If the field does not meet the requirements, a legend is displayed indicating it_ 
* When both fields meet the criteria, the "Register" button is enabled
* Clicking on the "Register" button executes an http request to the server with the mail and password as body

**Comment by CristianCazares** [comment]
Solved with: #4
